.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2016 Mike Hingley <computa_mike@hotmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH Selfietorium 1 "December 14 2016"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
selfietorium \- A system for setting up a party photobooth
.SH SYNOPSIS
.B selfietorium
.br
.SH DESCRIPTION
This manual page documents briefly the
.B selfietorium
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBselfietorium\fP is a program that...
.SH OPTIONS
Selfietorium reads its configuration from a json formatted file - boothsettings.json.
For a complete description of the options within the boothsettings.json file, 
see the wiki hosted on github.
.PP 
.PP
wiki available at : https://github.com/TitaniumBunker/Selfietorium/wiki
.PP
