Document: selfietorium
Title: Debian selfietorium Manual
Author: <insert document author here>
Abstract: This manual describes what selfietorium is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/selfietorium/selfietorium.sgml.gz

Format: postscript
Files: /usr/share/doc/selfietorium/selfietorium.ps.gz

Format: text
Files: /usr/share/doc/selfietorium/selfietorium.text.gz

Format: HTML
Index: /usr/share/doc/selfietorium/html/index.html
Files: /usr/share/doc/selfietorium/html/*.html
